BEGIN;
CREATE TABLE watchlist (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title text NOT NULL,
    movie_id NUMERIC NOT NULL,
    user_id NUMERIC NOT NULL,
    release_date TEXT ,
    status TEXT,
    poster_path TEXT,
    runtime INTEGER, 
    genres TEXT NOT NULL
);
COMMIT;    
    